<?php

declare(strict_types=1);

namespace Cowegis\Core\Schema\Layer;

use Cowegis\Core\Schema\GeoJson\FeatureCollectionSchema;
use Cowegis\Core\Schema\LayerSchemaDescriber;
use Cowegis\Core\Schema\SchemaBuilder;
use GoldSpecDigital\ObjectOrientedOAS\Objects\OneOf;
use GoldSpecDigital\ObjectOrientedOAS\Objects\Schema;

class GeoJsonLayerDescriber extends LayerSchemaDescriber
{
    protected function requiredProperties(SchemaBuilder $specificationBuilder) : array
    {
        $reference = $specificationBuilder->components()->withSchema(
            OneOf::create('data')
                ->schemas(
                    Schema::string()->format('url'),
                    Schema::ref(FeatureCollectionSchema::FULL_REF)
                ),
            'GeoJsonLayerData'
        );

        return [
            $reference->objectId('data')
        ];
    }

    protected function optionalProperties(SchemaBuilder $specificationBuilder) : array
    {
        return parent::optionalProperties($specificationBuilder); // TODO: Change the autogenerated stub
    }

    protected function registerRequirements(SchemaBuilder $specificationBuilder, Schema $schema) : void
    {
        parent::registerRequirements($specificationBuilder, $schema); // TODO: Change the autogenerated stub
    }
}
